services:
    db:
        image: postgres:18
        container_name: panel_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mydb
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql
    mc_server:
        build: ./PPanelPlugin
        container_name: mc_server
        ports:
            - "25565:25565"
        depends_on:
            - db
    panel:
        build: ./PWebsitePanel
        container_name: panel
        ports:
            - "8080:8080"
        depends_on:
            - db
            - mc_server
        environment:
            JWT_KEY_PUBLICPROJECT: [TOKEN HERE]
            spring.datasource.url: jdbc:postgresql://db:5432/mydb
            public-projects.web-panel.plugin-host: mc_server
            public-projects.web-panel.plugin-port: 9876
    frontend:
        build: ./PFrontend
        container_name: frontend
        ports:
            - "4173:4173"
            - "5173:5173"
        depends_on:
            - panel
volumes:
    pgdata: