spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

public-projects.web-panel.jwt-key=${JWT_KEY_PUBLICPROJECT}
public-projects.web-panel.jwt-name=webpanel
public-projects.web-panel.jwt-time=3600
public-projects.web-panel.jwt-secure-property=false