name: Test CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22
          cache: gradle
      - name: Gradlew chmod
        run: chmod +x gradlew
      - name: Gradle test
        run: ./gradlew clean test